#!/bin/bash
cd /home/wuyong/project/liming/CaudateGWAS/data
#awk -vOFS="\t" 'BEGIN{print "SNP\tA1\tA2\tfreq\tb\tse\tp\tn"}{print $1,$3,$4,$5,$6,$7,$8,$9}' ENIGMA2Caudate.txt | sed '2d' >ENIGMA2Caudate.smr
#cat /home/wuyong/data/SMR/*.freq | grep -v ',' | perl -e 'my %id; open IN, $ARGV[0] or die; while(<IN>){chomp; my @a=split(/\t/, $_);$id{$a[2]}=[$a[3],$a[5]];}close IN; open IN, $ARGV[1] or die; while(<IN>){chomp; my @a=split(/\t/, $_); if(exists $id{$a[1]} && $id{$a[1]}[0] eq $a[4]){my $freq = 1-$id{$a[0]}[1]; print "$a[1]\t$a[4]\t$a[3]\t$freq\t$a[5]\t$a[6]\t$a[12]\t38851\n";}elsif(exists $id{$a[1]} && $id{$a[1]}[0] ne $a[4]){print "$a[1]\t$a[4]\t$a[3]\t$id{$a[1]}[1]\t$a[5]\t$a[6]\t$a[12]\t38851\n";}}close IN;' - LeftCaudateVolume_buildGRCh37.tsv | awk -vOFS="\t" 'BEGIN{print "SNP","A1","A2","freq","b","se","p","n"}{print $0}' >LeftCaudateVolume.SMR
#cat /home/wuyong/data/SMR/*.freq | grep -v ',' | perl -e 'my %id; open IN, $ARGV[0] or die; while(<IN>){chomp; my @a=split(/\t/, $_);$id{$a[2]}=[$a[3],$a[5]];}close IN; open IN, $ARGV[1] or die; while(<IN>){chomp; my @a=split(/\t/, $_); if(exists $id{$a[1]} && $id{$a[1]}[0] eq $a[4]){my $freq = 1-$id{$a[0]}[1]; print "$a[1]\t$a[4]\t$a[3]\t$freq\t$a[5]\t$a[6]\t$a[12]\t38851\n";}elsif(exists $id{$a[1]} && $id{$a[1]}[0] ne $a[4]){print "$a[1]\t$a[4]\t$a[3]\t$id{$a[1]}[1]\t$a[5]\t$a[6]\t$a[12]\t38851\n";}}close IN;' - RightCaudateVolume_buildGRCh37.tsv | awk -vOFS="\t" 'BEGIN{print "SNP","A1","A2","freq","b","se","p","n"}{print $0}' >RightCaudateVolume.SMR

cd /home/wuyong/project/liming/CaudateGWAS/result
smr_Linux --bfile /home/wuyong/data/SMR/1000G_all_chrs.hwe.geno.mind.filtered.EUR --gwas-summary /home/wuyong/project/liming/CaudateGWAS/data/ENIGMA2Caudate.smr --beqtl-summary /home/wuyong/data/Caudate_eQTL/eqtl_tables/caudate_eqtl_Gene --out SMR_ENIGMA2Caudate_CaudateGene --thread-num 20 --diff-freq 1 --diff-freq-prop 1 --peqtl-smr 5e-3
smr_Linux --bfile /home/wuyong/data/SMR/1000G_all_chrs.hwe.geno.mind.filtered.EUR --gwas-summary /home/wuyong/project/liming/CaudateGWAS/data/ENIGMA2Caudate.smr --beqtl-summary /home/wuyong/data/Caudate_eQTL/eqtl_tables/caudate_eqtl_Exon --out SMR_ENIGMA2Caudate_CaudateExon --thread-num 20 --diff-freq 1 --diff-freq-prop 1 --peqtl-smr 5e-3
smr_Linux --bfile /home/wuyong/data/SMR/1000G_all_chrs.hwe.geno.mind.filtered.EUR --gwas-summary /home/wuyong/project/liming/CaudateGWAS/data/ENIGMA2Caudate.smr --beqtl-summary /home/wuyong/data/Caudate_eQTL/eqtl_tables/caudate_eqtl_Junction --out SMR_ENIGMA2Caudate_CaudateJunction --thread-num 20 --diff-freq 1 --diff-freq-prop 1 --peqtl-smr 5e-3
smr_Linux --bfile /home/wuyong/data/SMR/1000G_all_chrs.hwe.geno.mind.filtered.EUR --gwas-summary /home/wuyong/project/liming/CaudateGWAS/data/ENIGMA2Caudate.smr --beqtl-summary /home/wuyong/data/Caudate_eQTL/eqtl_tables/caudate_eqtl_Transcript --out SMR_ENIGMA2Caudate_CaudateTranscript --thread-num 20 --diff-freq 1 --diff-freq-prop 1 --peqtl-smr 5e-3

smr_Linux --bfile /home/wuyong/data/SMR/1000G_all_chrs.hwe.geno.mind.filtered.EUR --gwas-summary /home/wuyong/project/liming/CaudateGWAS/data/LeftCaudateVolume.SMR --beqtl-summary /home/wuyong/data/Caudate_eQTL/eqtl_tables/caudate_eqtl_Gene --out SMR_LeftCaudateVolume_CaudateGene --thread-num 20 --diff-freq 1 --diff-freq-prop 1 --peqtl-smr 5e-3
smr_Linux --bfile /home/wuyong/data/SMR/1000G_all_chrs.hwe.geno.mind.filtered.EUR --gwas-summary /home/wuyong/project/liming/CaudateGWAS/data/LeftCaudateVolume.SMR --beqtl-summary /home/wuyong/data/Caudate_eQTL/eqtl_tables/caudate_eqtl_Exon --out SMR_LeftCaudateVolume_CaudateExon --thread-num 20 --diff-freq 1 --diff-freq-prop 1 --peqtl-smr 5e-3
smr_Linux --bfile /home/wuyong/data/SMR/1000G_all_chrs.hwe.geno.mind.filtered.EUR --gwas-summary /home/wuyong/project/liming/CaudateGWAS/data/LeftCaudateVolume.SMR --beqtl-summary /home/wuyong/data/Caudate_eQTL/eqtl_tables/caudate_eqtl_Junction --out SMR_LeftCaudateVolume_CaudateJunction --thread-num 20 --diff-freq 1 --diff-freq-prop 1 --peqtl-smr 5e-3
smr_Linux --bfile /home/wuyong/data/SMR/1000G_all_chrs.hwe.geno.mind.filtered.EUR --gwas-summary /home/wuyong/project/liming/CaudateGWAS/data/LeftCaudateVolume.SMR --beqtl-summary /home/wuyong/data/Caudate_eQTL/eqtl_tables/caudate_eqtl_Transcript --out SMR_LeftCaudateVolume_CaudateTranscript --thread-num 20 --diff-freq 1 --diff-freq-prop 1 --peqtl-smr 5e-3

smr_Linux --bfile /home/wuyong/data/SMR/1000G_all_chrs.hwe.geno.mind.filtered.EUR --gwas-summary /home/wuyong/project/liming/CaudateGWAS/data/RightCaudateVolume.SMR --beqtl-summary /home/wuyong/data/Caudate_eQTL/eqtl_tables/caudate_eqtl_Gene --out SMR_RightCaudateVolume_CaudateGene --thread-num 20 --diff-freq 1 --diff-freq-prop 1 --peqtl-smr 5e-3
smr_Linux --bfile /home/wuyong/data/SMR/1000G_all_chrs.hwe.geno.mind.filtered.EUR --gwas-summary /home/wuyong/project/liming/CaudateGWAS/data/RightCaudateVolume.SMR --beqtl-summary /home/wuyong/data/Caudate_eQTL/eqtl_tables/caudate_eqtl_Exon --out SMR_RightCaudateVolume_CaudateExon --thread-num 20 --diff-freq 1 --diff-freq-prop 1 --peqtl-smr 5e-3
smr_Linux --bfile /home/wuyong/data/SMR/1000G_all_chrs.hwe.geno.mind.filtered.EUR --gwas-summary /home/wuyong/project/liming/CaudateGWAS/data/RightCaudateVolume.SMR --beqtl-summary /home/wuyong/data/Caudate_eQTL/eqtl_tables/caudate_eqtl_Junction --out SMR_RightCaudateVolume_CaudateJunction --thread-num 20 --diff-freq 1 --diff-freq-prop 1 --peqtl-smr 5e-3
smr_Linux --bfile /home/wuyong/data/SMR/1000G_all_chrs.hwe.geno.mind.filtered.EUR --gwas-summary /home/wuyong/project/liming/CaudateGWAS/data/RightCaudateVolume.SMR --beqtl-summary /home/wuyong/data/Caudate_eQTL/eqtl_tables/caudate_eqtl_Transcript --out SMR_RightCaudateVolume_CaudateTranscript --thread-num 20 --diff-freq 1 --diff-freq-prop 1 --peqtl-smr 5e-3
